# Generated by Django 3.2.9 on 2021-11-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
