FROM ubuntu:18.04

WORKDIR /usr/src/app

COPY requirements/requirements.txt ./

RUN apt-get update -y \
    && apt-get install software-properties-common -y\
    && add-apt-repository ppa:deadsnakes/ppa -y\
    && apt-get install python3.9 -y\
    && apt-get install python3-pip -y\
    && apt-get install libmysqlclient-dev -y

RUN pip3 install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "scheduler.py"]
