FROM python:3.9

MAINTAINER eslerkang <eslerkang@gmail.com>

WORKDIR /usr/src/app

COPY requirements/requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "weasley.wsgi:application"]
